07.06.2025 12:14 [USER 963729102 LOG!!] Traceback (most recent call last):
07.06.2025 12:14 [USER 963729102 LOG!!] File "/home/step/Desktop/code/server/users/963729102/main.py", line 10, in <module>
07.06.2025 12:14 [USER 963729102 LOG!!] import pandas
07.06.2025 12:14 [USER 963729102 LOG!!] ModuleNotFoundError: No module named 'pandas'
